import { logInfo, logError } from "./logger.js";

export interface EmailParams {
  to: string;
  subject: string;
  html: string;
  attachments?: { filename: string; content: Buffer; contentType?: string }[];
}

async function sendViaSMTP(params: EmailParams): Promise<boolean> {
  const host = process.env.ZOHO_SMTP_HOST ?? "smtp.zoho.com";
  const port = Number(process.env.ZOHO_SMTP_PORT ?? 465);
  const user = process.env.ZOHO_SMTP_USER ?? "";
  const pass = process.env.ZOHO_SMTP_PASS ?? "";
  const from = process.env.ZOHO_SMTP_FROM ?? user;

  if (!user || !pass) {
    logError("email/smtp", "ZOHO_SMTP_USER and ZOHO_SMTP_PASS required");
    return false;
  }

  try {
    const nodemailer = await import("nodemailer");
    const transporter = nodemailer.default.createTransport({
      host,
      port,
      secure: port === 465,
      auth: { user, pass },
    });

    await transporter.sendMail({
      from,
      to: params.to,
      subject: params.subject,
      html: params.html,
      attachments: params.attachments,
    });

    logInfo(`email/smtp sent to ${params.to}`);
    return true;
  } catch (e) {
    logError("email/smtp", e);
    return false;
  }
}

export async function sendReportEmail(
  to: string,
  name: string,
  downloadUrl: string,
  reportType: string,
  amount: number,
  paymentId: string,
): Promise<boolean> {
  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: Georgia, serif; color: #1a1a1a; max-width: 600px; margin: 0 auto; padding: 2rem;">
  <h1 style="color: #8b4513; border-bottom: 2px solid #d4a373; padding-bottom: 0.5rem;">Your Kundali Report is Ready</h1>
  <p>Hi ${name || "there"},</p>
  <p>Thank you for your purchase. Your <strong>${reportType}</strong> report has been generated and is ready for download.</p>
  
  <div style="background: #faf3e8; border: 1px solid #d4a373; border-radius: 8px; padding: 1.5rem; margin: 1.5rem 0;">
    <p style="margin: 0 0 0.5rem 0;"><strong>Amount Paid:</strong> ₹${amount}</p>
    <p style="margin: 0 0 0.5rem 0;"><strong>Payment ID:</strong> ${paymentId}</p>
    <p style="margin: 0;"><strong>Report Type:</strong> ${reportType}</p>
  </div>

  <a href="${downloadUrl}" style="display: inline-block; background: #8b4513; color: white; padding: 0.8rem 2rem; text-decoration: none; border-radius: 4px; font-weight: 600;">Download Full Report (PDF)</a>
  
  <p style="margin-top: 2rem; font-size: 0.9rem; color: #666;">This link will remain active for 7 days. If you have any issues, email us at <a href="mailto:support@shrikundali.com" style="color: #8b4513">support@shrikundali.com</a>.</p>
  
  <hr style="border: none; border-top: 1px solid #d4a373; margin: 2rem 0;">
  <p style="font-size: 0.8rem; color: #888; text-align: center;">Generated by Shri Kundali &bull; <a href="https://shrikundali.in/disclaimer" style="color: #888;">For guidance, not a substitute for professional advice</a></p>
</body>
</html>`;

  return sendViaSMTP({
    to,
    subject: `Your Kundali Report — Payment Confirmed (₹${amount})`,
    html,
  });
}

export async function sendPaymentFailureEmail(
  to: string,
  name: string,
  error: string,
): Promise<boolean> {
  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: Georgia, serif; color: #1a1a1a; max-width: 600px; margin: 0 auto; padding: 2rem;">
  <h1 style="color: #8b4513;">Payment Received — Report Generation Pending</h1>
  <p>Hi ${name || "there"},</p>
  <p>We received your payment, but encountered a technical issue while generating your report.</p>
  <p>Our team has been notified and will resolve this shortly. You will receive your report via email within the next 30 minutes.</p>
  <p>If you don't receive it, please contact us with your payment details.</p>
  <hr style="border: none; border-top: 1px solid #d4a373; margin: 2rem 0;">
  <p style="font-size: 0.8rem; color: #888; text-align: center;">Shri Kundali Support</p>
</body>
</html>`;

  return sendViaSMTP({
    to,
    subject: "Your Kundali Report — Processing",
    html,
  });
}
