import type { KundliData } from "./prokerala.js";

/* ── helpers ──────────────────────────────────────────── */

function val(obj: unknown, path: string): unknown {
  return path.split(".").reduce<unknown>((o, k) => (o && typeof o === "object" ? (o as Record<string, unknown>)[k] : undefined), obj);
}

function str(v: unknown, fallback = "N/A"): string {
  if (v == null || v === "") return fallback;
  return String(v);
}

function dateStr(v: unknown): string {
  if (!v) return "N/A";
  try { return new Date(String(v)).toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" }); }
  catch { return String(v); }
}

function list(obj: unknown, key: string): Record<string, unknown>[] {
  if (!obj || typeof obj !== "object") return [];
  const raw = (obj as Record<string, unknown>)[key];
  return Array.isArray(raw) ? (raw as Record<string, unknown>[]) : [];
}

/* ── markdown ─────────────────────────────────────────── */

export function renderMarkdown(data: KundliData, label?: string): string {
  const d = data.data;
  const title = label || "Janam Kundali Report";
  const lines: string[] = [];

  lines.push(`# ${title}\n`);

  // Birth details from nakshatra_details
  const nd = val(d, "nakshatra_details") as Record<string, unknown> | undefined;
  if (nd) {
    lines.push("## Birth Details\n");
    lines.push(`| Field | Value |`);
    lines.push(`|-------|-------|`);
    lines.push(`| Nakshatra | ${str(val(nd, "nakshatra_name"))} |`);
    lines.push(`| Nakshatra Pad | ${str(val(nd, "nakshatra_pada"))} |`);
    lines.push(`| Rashi | ${str(val(nd, "rashi_name"))} |`);
    lines.push(`| Lagna (Ascendant) | ${str(val(nd, "lagna_name"))} |`);
    lines.push(`| Ayurvedic Kapha | ${str(val(nd, "ayurvedic_name"))} |`);
    lines.push("");
  }

  // Mangal Dosha
  const md = val(d, "mangal_dosha") as Record<string, unknown> | undefined;
  if (md) {
    lines.push("## Mangal Dosha\n");
    const has = val(md, "is_manglik");
    lines.push(`- **Has Mangal Dosha:** ${has ? "Yes" : "No"}`);
    lines.push("");
  }

  // Yoga details
  const yogas = list(d, "yoga_details");
  if (yogas.length > 0) {
    lines.push("## Yogas\n");
    for (const y of yogas) {
      const name = str(val(y, "yoga_name") ?? val(y, "name"));
      const desc = str(val(y, "description") ?? val(y, "effects"));
      lines.push(`### ${name}\n`);
      if (desc) lines.push(`${desc}\n`);
    }
  }

  // Planet positions (if available in extended data)
  const planets = list(d, "planet_positions") ?? list(d, "planets");
  if (planets.length > 0) {
    lines.push("## Planet Positions\n");
    lines.push("| Planet | Sign | Degree | House | Nakshatra |");
    lines.push("|--------|------|--------|-------|-----------|");
    for (const p of planets) {
      lines.push(`| ${str(val(p, "planet_name") ?? val(p, "name"))} | ${str(val(p, "sign_name") ?? val(p, "rashi"))} | ${str(val(p, "degree"))} | ${str(val(p, "house"))} | ${str(val(p, "nakshatra_name"))} |`);
    }
    lines.push("");
  }

  // Raw JSON fallback
  if (lines.length <= 3) {
    lines.push("## Raw Data\n");
    lines.push("```json");
    lines.push(JSON.stringify(d, null, 2));
    lines.push("```");
  }

  lines.push(`\n---\n*Generated by Shri Kundali API*`);
  return lines.join("\n");
}

/* ── HTML ─────────────────────────────────────────────── */

export function renderHTML(data: KundliData, label?: string): string {
  const md = renderMarkdown(data, label);
  const htmlBody = md
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/^\| (.+?) \|$/gm, (m) => {
      const cells = m.split("|").filter(Boolean).map((c) => c.trim());
      return cells.map((c) => `<td>${c}</td>`).join("");
    })
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/^---$/gm, "<hr>")
    .replace(/\n{2,}/g, "</p><p>")
    .replace(/^```json\n([\s\S]*?)\n```$/gm, "<pre><code>$1</code></pre>")
    .replace(/\n/g, "<br>");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${label || "Janam Kundali Report"}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Georgia, serif; color: #1a1a1a; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; }
  h1 { font-size: 1.8rem; color: #8b4513; border-bottom: 2px solid #d4a373; padding-bottom: 0.5rem; margin-bottom: 1rem; }
  h2 { font-size: 1.3rem; color: #6b3a0e; margin-top: 1.5rem; margin-bottom: 0.5rem; }
  h3 { font-size: 1.1rem; color: #8b4513; margin-top: 1rem; }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
  th, td { border: 1px solid #d4a373; padding: 0.4rem 0.6rem; text-align: left; font-size: 0.9rem; }
  th { background: #faf3e8; font-weight: 600; }
  tr:nth-child(even) { background: #fdf8f0; }
  li { margin-left: 1.5rem; }
  pre { background: #f5f0e8; padding: 1rem; border-radius: 4px; overflow-x: auto; font-size: 0.85rem; }
  code { font-family: monospace; background: #f5f0e8; padding: 0.1rem 0.3rem; border-radius: 2px; font-size: 0.85rem; }
  hr { border: none; border-top: 1px solid #d4a373; margin: 2rem 0; }
  .footer { text-align: center; color: #888; font-size: 0.8rem; margin-top: 2rem; }
</style>
</head>
<body>
<p>${htmlBody}</p>
<div class="footer">Generated by Shri Kundali API</div>
</body>
</html>`;
}

/* ── PDF (via html-pdf-node dynamic import) ───────────── */

export async function renderPDF(data: KundliData, label?: string): Promise<Buffer> {
  const html = renderHTML(data, label);
  const htmlPdf = (await import("html-pdf-node")).default;
  const file = { content: html };
  const options = { format: "A4", margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" } };
  const pdf = await htmlPdf.generatePdf(file, options);
  return Buffer.from(pdf);
}
